version: "3.7"

services:
  database:
    image: postgres
    container_name: database_nestjs_alura
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=nestjs
      - POSTGRES_DB=books
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
